export type Arcana = "major" | "minor";
export type Suit = "wands" | "cups" | "swords" | "pentacles";

export interface TarotCard {
  slug: string;
  name: string;
  number: number;        // 0–21 for major, 1–14 for minor
  arcana: Arcana;
  suit?: Suit;
  image: string;         // /cards/<slug>.jpg
  keywords: string[];
  upright: string;
  reversed: string;
  love: string;
  career: string;
  advice: string;
}

const M = (
  number: number, slug: string, name: string,
  keywords: string[], upright: string, reversed: string,
  love: string, career: string, advice: string
): TarotCard => ({
  slug, name, number, arcana: "major", image: `/cards/${slug}.jpg`,
  keywords, upright, reversed, love, career, advice,
});

const m = (
  suit: Suit, number: number, slug: string, name: string,
  keywords: string[], upright: string, reversed: string,
  love: string, career: string, advice: string
): TarotCard => ({
  slug, name, number, arcana: "minor", suit, image: `/cards/${slug}.jpg`,
  keywords, upright, reversed, love, career, advice,
});

export const deck: TarotCard[] = [
  // ============ MAJOR ARCANA ============
  M(0, "the-fool", "The Fool",
    ["new beginnings", "innocence", "spontaneity", "free spirit"],
    "A new chapter is opening before you. The Fool invites you to step into the unknown with curiosity rather than fear — trust that the ground will appear as you walk.",
    "Recklessness, fear of change, holding back from a leap that needs to be taken. The Fool reversed warns against ignoring real risks or refusing to grow up.",
    "A fresh romantic chapter or unexpected meeting. Approach with openness and play, but do not skip the slow work of building trust.",
    "An opportunity to begin something new — a role, a project, a path. Worth the risk if your heart is in it.",
    "Say yes to something unexpected today. The leap is the lesson."),

  M(1, "the-magician", "The Magician",
    ["manifestation", "power", "intention", "skill"],
    "You have everything you need within reach. The Magician reminds you that intention, focus, and action together turn possibility into reality.",
    "Manipulation, scattered energy, talent unused. Or someone whose words and actions do not match.",
    "A magnetic, communicative connection. Speak your truth clearly — and listen for whether theirs holds up.",
    "Time to manifest. Pick one goal and apply your full toolkit. You are more capable than you assume.",
    "Take one concrete action toward your goal today. Stop strategizing, start moving."),

  M(2, "the-high-priestess", "The High Priestess",
    ["intuition", "mystery", "subconscious", "inner wisdom"],
    "The answer you seek is already within you. The High Priestess asks you to trust your inner voice over external noise.",
    "Secrets held too long, intuition ignored, disconnection from your own depth.",
    "A relationship with hidden currents. Pay attention to what is not being said.",
    "A situation that requires patience and reading between the lines. Avoid forcing a conclusion.",
    "Pause before responding. Listen to what you actually feel, not what you think you should feel."),

  M(3, "the-empress", "The Empress",
    ["abundance", "nurturing", "creativity", "femininity"],
    "A season of creativity and nurturing is unfolding. The Empress speaks of growth — in relationships, projects, and the gentle abundance of being cared for.",
    "Creative block, neglect (of self or others), suffocating dependence, blocked femininity.",
    "Deepening intimacy, possibly the start of family. Sensual, generous, and warm.",
    "A creative project comes to fruition. Or recognition for nurturing work you have quietly done.",
    "Tend to something you love. Watch what blooms when you give it attention."),

  M(4, "the-emperor", "The Emperor",
    ["structure", "authority", "stability", "discipline"],
    "It is time to build firm foundations. The Emperor calls for clarity, boundaries, and the steady authority of taking ownership of your domain.",
    "Rigid control, domination, abuse of power, or absence of needed structure.",
    "A stable, committed partner — or a need to bring more structure and reliability into your love life.",
    "Leadership opportunity, or the need to assert yourself. Build the framework others can rely on.",
    "Make one decision you have been putting off. Indecision is a decision in disguise."),

  M(5, "the-hierophant", "The Hierophant",
    ["tradition", "wisdom", "conformity", "teaching"],
    "Wisdom passed down has value. The Hierophant points to mentors, established paths, and the comfort of belonging to something larger than yourself.",
    "Rebellion (welcome or destructive), questioning dogma, or stale conformity.",
    "Conventional commitment — engagement, marriage, or formalizing a relationship.",
    "Mentorship, formal training, or working within an established institution. Slow but steady gains.",
    "Seek counsel from someone you respect. Tradition is not always wrong."),

  M(6, "the-lovers", "The Lovers",
    ["love", "choice", "harmony", "values alignment"],
    "A meaningful choice is before you — about love, partnership, or aligning your actions with your deepest values. The Lovers asks: what is true for you?",
    "Misalignment, indecision, a choice made for the wrong reasons. Or imbalance in a partnership.",
    "Deep romantic connection or a relationship-defining choice. Trust attraction, but choose with the whole self.",
    "A choice between two paths. The right one is the one that aligns with your values, not just your ambition.",
    "Choose with your heart, not your fear. The fear-based answer is rarely the true one."),

  M(7, "the-chariot", "The Chariot",
    ["determination", "willpower", "victory", "control"],
    "Forward motion is within your power. The Chariot speaks of focused will, victory through discipline, and steering your life with intention.",
    "Loss of direction, scattered energy, or aggression where steadiness was needed.",
    "Pursuing what you want with confidence — or a partnership pulled in two directions that needs realignment.",
    "Victory through perseverance. Stay focused; the finish line is closer than it feels.",
    "Move toward your goal with steady force. Doubt is a passenger, not a driver."),

  M(8, "strength",
    "Strength",
    ["inner power", "courage", "compassion", "patience"],
    "Quiet strength outlasts brute force. This card honors the courage of patience, compassion, and meeting hard moments with an open heart.",
    "Self-doubt, repressed anger, fear masquerading as toughness.",
    "A bond that endures hard seasons. Lean into vulnerability; it is the bridge.",
    "You are more equipped than you think. Lead from calm authority, not anxiety.",
    "Respond with gentleness today — especially to yourself."),

  M(9, "the-hermit", "The Hermit",
    ["introspection", "solitude", "guidance", "inner truth"],
    "A season of inner work is calling. The Hermit values solitude — not loneliness, but the spaciousness needed to hear yourself clearly.",
    "Isolation, withdrawal that has become avoidance, refusal of help.",
    "Time alone may be exactly what your relationship needs. Or a partner is seeking solitude — let them.",
    "A pause before the next chapter. Reflect on what you actually want.",
    "Take fifteen minutes alone today. No phone. No agenda."),

  M(10, "wheel-of-fortune", "Wheel of Fortune",
    ["cycles", "destiny", "change", "turning point"],
    "Change is the only constant. The Wheel reminds you that what rises will fall, what falls will rise — and your task is to ride the turn with grace.",
    "Bad luck, resistance to change, feeling stuck in a cycle.",
    "A relationship is at a turning point. Whatever the direction, momentum is real.",
    "Unexpected opportunity or shift. Stay light on your feet.",
    "Release what you cannot control. The wheel turns whether you grip it or not."),

  M(11, "justice", "Justice",
    ["truth", "fairness", "cause and effect", "accountability"],
    "Balance is being restored. Justice asks for honesty — with others and yourself — and reminds you that fair outcomes follow fair actions.",
    "Unfairness, dishonesty, avoiding accountability, legal trouble.",
    "Honesty is needed. The relationship will be healthier on the other side of the hard conversation.",
    "A fair outcome to a long process. Or the consequences of a past choice landing now.",
    "Tell one truth you have been avoiding. Clarity is a kindness."),

  M(12, "the-hanged-man", "The Hanged Man",
    ["surrender", "new perspective", "pause", "sacrifice"],
    "A new perspective requires letting go of the old one. The Hanged Man invites you to pause, suspend judgement, and see the situation upside down.",
    "Stagnation, martyrdom, refusing to let go, indecision dragged out too long.",
    "A pause that lets the relationship breathe — or a sacrifice that has cost too much.",
    "Hit pause. Forcing this now will only delay the real answer.",
    "Stop pushing. Let the answer come to you."),

  M(13, "death", "Death",
    ["transformation", "endings", "rebirth", "letting go"],
    "An ending is making space for something new. Death is rarely literal in tarot — it speaks of necessary endings, shedding what no longer fits.",
    "Resistance to change, stagnation, fear of letting go.",
    "An ending — possibly painful, possibly liberating. What is no longer alive cannot be revived.",
    "A chapter closes. Mourn it, then turn the page.",
    "Let one thing go today. Without explanation."),

  M(14, "temperance", "Temperance",
    ["balance", "moderation", "patience", "purpose"],
    "Blend what seems opposite. Temperance is the art of moderation, patience, and finding the middle path where extremes once ruled.",
    "Imbalance, excess, impatience, mismatched priorities.",
    "Calm, blended partnership. Two people meeting in the middle gracefully.",
    "Steady progress. The slow path is the right one.",
    "Choose the calmer response. Speed is rarely wisdom."),

  M(15, "the-devil", "The Devil",
    ["attachment", "addiction", "shadow", "materialism"],
    "You are freer than you believe. The Devil reveals the chains we accept — habits, fears, dependencies — and the truth that the lock is on the inside.",
    "Breaking free, recognizing toxicity, releasing an addiction or unhealthy attachment.",
    "Intense chemistry that may not be healthy. Or a pattern that keeps repeating.",
    "Beware the golden cage. Money or status that costs you yourself is too expensive.",
    "Name one pattern you are ready to break. Naming is half the work."),

  M(16, "the-tower", "The Tower",
    ["sudden change", "revelation", "upheaval", "awakening"],
    "Something must fall to make way for what is true. The Tower clears illusions quickly — uncomfortable in the moment, liberating in retrospect.",
    "Avoided disaster, resisting a needed collapse, fear of the inevitable.",
    "A relationship shaken to its foundation. Whatever survives is real.",
    "Disruption — but the structure that falls was not serving you anyway.",
    "Trust the disruption. It is clearing the path."),

  M(17, "the-star", "The Star",
    ["hope", "renewal", "healing", "faith"],
    "After the storm, the still waters. The Star is a card of healing, renewal, and quiet faith — the kind that returns slowly and stays.",
    "Lost faith, despair, disconnection from your own light.",
    "Healing in love. A gentle, hopeful season.",
    "Inspiration returns. Renewed purpose after a hard stretch.",
    "Let yourself believe again. Faith is a muscle."),

  M(18, "the-moon", "The Moon",
    ["mystery", "intuition", "illusion", "subconscious"],
    "Not everything is as it appears. The Moon asks you to navigate by intuition and patience — clarity will come when the fog lifts on its own.",
    "Confusion clearing, secrets surfacing, fear dissolving.",
    "Uncertainty in love. Something hidden is asking to be seen.",
    "Trust your instincts even when the facts are unclear. The full picture is not yet visible.",
    "Hold the question. Do not force the answer."),

  M(19, "the-sun", "The Sun",
    ["joy", "success", "vitality", "clarity"],
    "Warmth, clarity, and well-being are with you. The Sun is one of the deck's most generous cards — celebrating presence, success, and being fully seen.",
    "Temporary clouds, delayed joy, self-doubt despite outward success.",
    "A radiant, joyful connection. Or a relationship coming into its full bloom.",
    "Recognition, success, the satisfaction of being seen for your work.",
    "Notice what is going right today. Gratitude is not naivety."),

  M(20, "judgement", "Judgement",
    ["awakening", "reckoning", "renewal", "calling"],
    "A calling is rising. Judgement marks moments of reckoning — looking honestly at the past and answering the question: who am I becoming?",
    "Self-judgement, refusing the call, fear of facing the past.",
    "A second chance. An old love reappears, or a buried conversation surfaces.",
    "A turning point — the work you have done is being recognized.",
    "Forgive yourself for an older version of you. They did their best with what they had."),

  M(21, "the-world", "The World",
    ["completion", "wholeness", "fulfillment", "integration"],
    "A cycle closes with wholeness. The World honors what you have built — and prepares you for the next beginning, wiser than before.",
    "A cycle dragging on, unfinished business, fear of completion.",
    "A whole, integrated partnership. Or a long chapter coming to a satisfying close.",
    "Major achievement. A long-held goal completed.",
    "Celebrate a quiet victory. You earned it."),

  // ============ WANDS (Fire — passion, creation, action) ============
  m("wands", 1, "ace-of-wands", "Ace of Wands",
    ["inspiration", "new energy", "creative spark", "potential"],
    "A spark of inspiration ignites. The Ace of Wands signals new creative or passionate energy — the kind that makes you want to start something today.",
    "Delays, creative block, hesitation, a great idea that stays in your head.",
    "A new attraction or rekindled passion. Lean in.",
    "A new venture, project, or role with momentum behind it.",
    "Act on the spark while it is hot. Inspiration has an expiration date."),

  m("wands", 2, "two-of-wands", "Two of Wands",
    ["planning", "future vision", "decisions", "personal power"],
    "Standing at the edge of your world, planning the next one. The Two of Wands rewards bold, considered ambition.",
    "Fear of the unknown, playing too safe, indecision about the bigger picture.",
    "Considering whether to take the relationship to a new place.",
    "Strategic planning phase. Map the path before you take it.",
    "Make the bold plan. The map matters before the journey."),

  m("wands", 3, "three-of-wands", "Three of Wands",
    ["expansion", "foresight", "exploration", "ships coming in"],
    "Your efforts are setting sail. The Three of Wands speaks of expansion, long-term vision, and the patience of waiting for what you have launched.",
    "Delays, plans falling short, lack of foresight.",
    "A long-distance connection, or anticipation of growth.",
    "Expansion — possibly international or beyond your current circle.",
    "Look further ahead than the next month."),

  m("wands", 4, "four-of-wands", "Four of Wands",
    ["celebration", "homecoming", "harmony", "milestones"],
    "A moment of arrival. The Four of Wands honors achievements, homecomings, and the joy of shared milestones.",
    "Transition pains, postponed celebrations, conflict at home.",
    "Engagement, moving in, formalizing a partnership.",
    "A milestone reached. Take a moment to mark it before pushing on.",
    "Celebrate. Skipping the joy steals it from you."),

  m("wands", 5, "five-of-wands", "Five of Wands",
    ["conflict", "competition", "disagreement", "tension"],
    "Healthy friction or unhealthy chaos. The Five of Wands signals competition and clashing perspectives — sharpening or exhausting, depending on how you engage.",
    "Avoiding conflict, suppressed tension, internal turmoil.",
    "Petty arguments that feel bigger than they are.",
    "Competitive environment. Defend your ideas without making it personal.",
    "Pick your battles. Not every disagreement needs your energy."),

  m("wands", 6, "six-of-wands", "Six of Wands",
    ["victory", "recognition", "public success", "confidence"],
    "Well-earned recognition arrives. The Six of Wands celebrates visible success — the moment your work is publicly affirmed.",
    "Lack of recognition, falling from a high, ego problems.",
    "Pride in your partner or being celebrated by yours.",
    "Public win. Promotion, recognition, or a project landing well.",
    "Accept the praise without minimizing. You earned this."),

  m("wands", 7, "seven-of-wands", "Seven of Wands",
    ["defense", "perseverance", "standing your ground", "challenge"],
    "Holding your position against pressure. The Seven of Wands honors the courage of staying true when others push back.",
    "Giving up, overwhelmed by criticism, defensiveness without cause.",
    "Defending your relationship against outside opinions, or your boundaries within it.",
    "Standing by your work in the face of doubt. Trust your judgement.",
    "Hold the line. The pressure is the test."),

  m("wands", 8, "eight-of-wands", "Eight of Wands",
    ["movement", "speed", "messages", "swift change"],
    "Things move quickly now. The Eight of Wands signals fast progress, incoming news, and momentum that wants to be ridden.",
    "Delays, missed opportunities, frustration with slow progress.",
    "Sudden clarity or a long-awaited message arrives.",
    "Rapid developments. Stay responsive.",
    "Move quickly. The window is open now."),

  m("wands", 9, "nine-of-wands", "Nine of Wands",
    ["resilience", "boundary", "last stretch", "vigilance"],
    "Worn but not done. The Nine of Wands speaks of resilience after a long fight — the final push when you most want to stop.",
    "Burnout, paranoia, refusing help, exhaustion.",
    "Trust issues from past wounds shaping the present. Worth addressing.",
    "The home stretch. Tired, but the finish line is close.",
    "Rest, but do not quit. One more push."),

  m("wands", 10, "ten-of-wands", "Ten of Wands",
    ["burden", "responsibility", "overload", "hard work"],
    "Carrying more than your share. The Ten of Wands honors hard work — and warns that you are doing too much alone.",
    "Releasing burdens, delegating, letting go of unnecessary weight.",
    "An imbalance in giving. You are carrying the relationship.",
    "Overcommitted. Delegate or drop something.",
    "Put down what is not yours to carry."),

  m("wands", 11, "page-of-wands", "Page of Wands",
    ["curiosity", "fresh enthusiasm", "discovery", "young energy"],
    "A youthful, eager energy arrives. The Page of Wands sparks exploration and the courage to try something new.",
    "Immaturity, scattered enthusiasm, projects abandoned mid-flight.",
    "A flirtation, or a partner showing playful new energy.",
    "A new role or assignment that asks for fresh enthusiasm.",
    "Explore without committing yet. Discovery is the goal."),

  m("wands", 12, "knight-of-wands", "Knight of Wands",
    ["action", "passion", "adventure", "impulse"],
    "Bold, fiery, and ready to ride. The Knight of Wands rewards decisive action but warns against burning out.",
    "Recklessness, anger, half-finished projects, restless impatience.",
    "Whirlwind romance — exciting, but watch the pace.",
    "A bold move pays off — if you have prepared the ground.",
    "Move with passion, but bring strategy with you."),

  m("wands", 13, "queen-of-wands", "Queen of Wands",
    ["confidence", "warmth", "leadership", "magnetism"],
    "Confident, warm, and unmistakably herself. The Queen of Wands leads with charisma and an open heart.",
    "Jealousy, insecurity, demanding attention, dimming your own light.",
    "A magnetic, generous partner — or the call to be one.",
    "Lead with warmth. Your confidence draws people in.",
    "Stand fully in your light. Smaller versions help no one."),

  m("wands", 14, "king-of-wands", "King of Wands",
    ["vision", "leadership", "bold action", "natural authority"],
    "Visionary leadership in action. The King of Wands turns big ideas into movements, with both fire and discipline.",
    "Tyranny, impulsiveness, broken promises, leading without listening.",
    "A passionate, decisive partner. Or the need to bring vision to your love life.",
    "Time to lead. Articulate the vision and call others to it.",
    "Cast the vision. People follow conviction more than instructions."),

  // ============ CUPS (Water — emotion, love, intuition) ============
  m("cups", 1, "ace-of-cups", "Ace of Cups",
    ["new love", "emotional opening", "compassion", "intuition"],
    "A new wellspring of feeling. The Ace of Cups offers fresh emotional connection — to others, or to yourself.",
    "Emotional blockage, repressed feelings, love refused.",
    "New love, or a deepening of an existing bond. Let the feelings move.",
    "A creative or compassionate project that fills you up.",
    "Open your heart to one person today. Even briefly."),

  m("cups", 2, "two-of-cups", "Two of Cups",
    ["partnership", "mutual love", "connection", "harmony"],
    "Two cups raised in honor of each other. This is the card of true partnership — mutual, balanced, alive.",
    "Imbalance, communication breakdown, disconnection.",
    "A meaningful new partnership, or harmony restored in an old one.",
    "A collaboration that benefits both parties equally.",
    "Honor the partnership. Mutual care is its own reward."),

  m("cups", 3, "three-of-cups", "Three of Cups",
    ["celebration", "friendship", "community", "joy"],
    "Friends, laughter, and the joy of shared moments. The Three of Cups celebrates the community that holds you up.",
    "Gossip, jealousy, overindulgence, isolation.",
    "Friendships shaping romance, or a partner welcomed into your circle.",
    "Collaboration leads to celebration. Your team is your strength.",
    "Reach out to a friend you have missed."),

  m("cups", 4, "four-of-cups", "Four of Cups",
    ["apathy", "contemplation", "disconnection", "missed opportunity"],
    "Three cups in hand, a fourth offered — and unseen. The Four of Cups warns of taking blessings for granted.",
    "Re-engagement, accepting what is offered, gratitude returning.",
    "Boredom with what you have. The grass is greener if you water it.",
    "Disengagement at work. An offer is being missed.",
    "Look up. Something is being offered that you have not noticed."),

  m("cups", 5, "five-of-cups", "Five of Cups",
    ["grief", "loss", "regret", "what remains"],
    "Three cups spilled, two still standing. The Five of Cups honors grief — and reminds you what remains.",
    "Acceptance, moving forward, finding peace with the past.",
    "Mourning a loss. The right cups are still there if you turn around.",
    "A setback. Real, but not total. Salvage what you can.",
    "Grieve fully. Then turn around — not everything is lost."),

  m("cups", 6, "six-of-cups", "Six of Cups",
    ["nostalgia", "childhood", "innocence", "old friends"],
    "A warm look backward. The Six of Cups invites nostalgia, reconnection, and the gentleness of innocence.",
    "Stuck in the past, refusing to grow up, unhealthy attachment to old times.",
    "An old flame returns, or a long friendship deepens.",
    "A familiar opportunity returns. Or working with people from your past.",
    "Reconnect with someone from before. Old roots run deep."),

  m("cups", 7, "seven-of-cups", "Seven of Cups",
    ["choices", "fantasy", "options", "illusion"],
    "Seven cups, seven temptations. The Seven of Cups warns that abundance of options can become its own paralysis.",
    "Clarity, picking one path, separating fantasy from reality.",
    "Too many options or fantasies clouding what is actually possible.",
    "Too many projects, none of them committed to. Pick one.",
    "Choose. Even the wrong choice teaches more than no choice."),

  m("cups", 8, "eight-of-cups", "Eight of Cups",
    ["walking away", "seeking more", "abandonment", "transition"],
    "Leaving what is incomplete in search of what is true. The Eight of Cups honors the courage to walk away.",
    "Returning, second thoughts, fear of leaving.",
    "Walking away from what no longer fulfills. Or being walked away from.",
    "Leaving a stable position for something more meaningful. Brave.",
    "Walk away from what is half-fulfilling. Empty cups will not refill themselves."),

  m("cups", 9, "nine-of-cups", "Nine of Cups",
    ["satisfaction", "wishes fulfilled", "contentment", "gratitude"],
    "The wish card. The Nine of Cups celebrates the satisfaction of dreams realized, especially the emotional ones.",
    "Self-indulgence, smugness, materialism, dissatisfaction despite having much.",
    "Contentment in love. Or your relationship wish coming true.",
    "Success that genuinely satisfies. Savor it.",
    "Name your wish. Then thank what is already here."),

  m("cups", 10, "ten-of-cups", "Ten of Cups",
    ["happiness", "harmony", "family", "lasting love"],
    "A full life of love, family, and emotional richness. The Ten of Cups is the storybook ending — earned slowly.",
    "Broken family, disconnection at home, picture-perfect-but-empty.",
    "Lasting, deep family love. Or building toward it.",
    "Harmony at work. The team feels like a community.",
    "Build for the long view. The ten of cups is built one cup at a time."),

  m("cups", 11, "page-of-cups", "Page of Cups",
    ["creativity", "intuitive messages", "wonder", "emotional curiosity"],
    "A childlike opening to emotion and creativity. The Page of Cups brings inspiration, surprise messages, and tenderness.",
    "Immaturity, emotional flightiness, ignoring intuition.",
    "A sweet, playful early connection or message.",
    "A creative project asks for naive enthusiasm. Let it.",
    "Trust the soft hunch. It is data."),

  m("cups", 12, "knight-of-cups", "Knight of Cups",
    ["romance", "idealism", "offer", "charm"],
    "The romantic, the dreamer, the bearer of beautiful offers. The Knight of Cups arrives with feeling, sometimes with promises.",
    "Moodiness, broken promises, unrealistic ideals, charm without substance.",
    "A romantic offer or proposal. Test that the substance matches the poetry.",
    "An offer arrives — appealing, but read the details.",
    "Accept the offer if the substance matches the feeling."),

  m("cups", 13, "queen-of-cups", "Queen of Cups",
    ["intuition", "empathy", "emotional wisdom", "compassion"],
    "Deep emotional intelligence at home in itself. The Queen of Cups honors the wisdom of feeling fully without losing yourself.",
    "Codependence, emotional flooding, self-neglect by way of caring for everyone else.",
    "A deeply empathic partner. Or a call to listen more than you speak.",
    "Lead with empathy. The team needs feeling, not just facts.",
    "Feel it all — and stay rooted in yourself."),

  m("cups", 14, "king-of-cups", "King of Cups",
    ["emotional mastery", "calm", "diplomacy", "wise counsel"],
    "Emotional mastery without coldness. The King of Cups holds steady through storms, with kindness intact.",
    "Emotional manipulation, suppressed feeling, moodiness disguised as strength.",
    "A steady, emotionally mature partner. Or the call to be one.",
    "Diplomacy wins where confrontation would fail.",
    "Stay calm through the storm. Your steadiness is the lighthouse."),

  // ============ SWORDS (Air — thought, conflict, truth) ============
  m("swords", 1, "ace-of-swords", "Ace of Swords",
    ["clarity", "breakthrough", "truth", "new idea"],
    "A sharp, clean breakthrough in thinking. The Ace of Swords cuts through confusion with a single, decisive insight.",
    "Confusion, miscommunication, mental fog, ideas misused.",
    "A clarifying conversation. Truth on the table changes everything.",
    "A breakthrough idea. Write it down and act on it.",
    "Say the true thing, simply. Clarity is the gift."),

  m("swords", 2, "two-of-swords", "Two of Swords",
    ["indecision", "stalemate", "avoidance", "choice"],
    "Two swords crossed, eyes blindfolded. The Two of Swords names the cost of avoiding a decision.",
    "Decision made, blindfold removed, truth faced.",
    "An impasse. Avoiding the conversation only sharpens the swords.",
    "A stalled choice. Gather information, then decide.",
    "Make the call. Sitting in the middle is a decision in itself."),

  m("swords", 3, "three-of-swords", "Three of Swords",
    ["heartbreak", "grief", "painful truth", "betrayal"],
    "Heart pierced clean. The Three of Swords does not soften the pain of betrayal, loss, or hard truth — but acknowledges it as part of healing.",
    "Healing, releasing pain, forgiveness — of self or others.",
    "A painful truth or breakup. Felt fully, it eventually passes.",
    "Painful feedback. Sit with it before acting on it.",
    "Let yourself grieve. Skipping the pain only delays it."),

  m("swords", 4, "four-of-swords", "Four of Swords",
    ["rest", "recovery", "retreat", "stillness"],
    "Lay your swords down. The Four of Swords prescribes rest — not as luxury, but as necessity.",
    "Burnout, refusing to rest, restlessness that has become chronic.",
    "Take space in the relationship to recover. Not distance, just rest.",
    "Step back. Pushing through here means burnout next week.",
    "Rest. Productivity is not the same as worth."),

  m("swords", 5, "five-of-swords", "Five of Swords",
    ["conflict", "winning at a cost", "defeat", "ego"],
    "A win that is not worth winning. The Five of Swords warns against being right at the cost of the relationship.",
    "Reconciliation, lowering defenses, moving on from old wounds.",
    "A fight where everyone loses. Step back from being right.",
    "A political win that costs you allies. Reconsider the price.",
    "Choose connection over being right. The cost of winning may be too high."),

  m("swords", 6, "six-of-swords", "Six of Swords",
    ["transition", "moving forward", "passage", "healing journey"],
    "Quiet passage from rough waters to calmer shores. The Six of Swords honors the slow work of moving forward.",
    "Resistance to leaving, lingering in difficulty, unresolved baggage.",
    "Moving on together from a hard chapter. Or finally leaving one alone.",
    "A transition, possibly a move or change of team. Calmer waters ahead.",
    "Move forward gently. You do not have to be ready to begin."),

  m("swords", 7, "seven-of-swords", "Seven of Swords",
    ["deception", "stealth", "strategy", "betrayal"],
    "Slipping away with what is not yours. The Seven of Swords warns of deception — others', or your own with yourself.",
    "Truth coming out, confession, recovering what was taken.",
    "Dishonesty in the relationship. Speak plainly or step away.",
    "Strategy is fine; dishonesty is not. Watch the line.",
    "Be honest about what you are actually doing — first with yourself."),

  m("swords", 8, "eight-of-swords", "Eight of Swords",
    ["restriction", "self-limitation", "trapped feeling", "fear"],
    "Bound by swords that are not locked. The Eight of Swords reveals self-imposed limits and the door that is, in fact, open.",
    "Freedom, recognizing the trap, stepping out of fear.",
    "Feeling stuck in a dynamic that may have an exit you have not tried.",
    "Self-imposed limits at work. The promotion is more available than you think.",
    "Look at the locks. Most are not locked."),

  m("swords", 9, "nine-of-swords", "Nine of Swords",
    ["anxiety", "nightmares", "worry", "fear"],
    "The card of 3 a.m. The Nine of Swords names the spiral of anxious thought — and the importance of separating fear from fact.",
    "Anxiety lifting, sleep returning, hope after a dark night.",
    "Anxiety about the relationship overshadowing the relationship itself.",
    "Catastrophizing. The worry is louder than the actual stakes.",
    "Write the fear down. Most of it shrinks in daylight."),

  m("swords", 10, "ten-of-swords", "Ten of Swords",
    ["rock bottom", "endings", "release", "dawn after dark"],
    "The fall is complete. The Ten of Swords names the rock-bottom moment — and the only direction left is up.",
    "Recovery, healing, recognizing the worst is past.",
    "A definitive ending. The wound is real; healing begins now.",
    "A project ends. Sometimes the only way through is collapse and restart.",
    "Acknowledge the ending. The dawn comes."),

  m("swords", 11, "page-of-swords", "Page of Swords",
    ["curiosity", "vigilance", "mental energy", "new ideas"],
    "Sharp-eyed and asking questions. The Page of Swords is mental energy in its early form — curious, sometimes scattered, often onto something.",
    "Gossip, sharp tongue, paranoia, scattered thinking.",
    "Lively conversations or a partner pushing your thinking.",
    "Research mode. Ask questions before committing.",
    "Ask one more question before you decide."),

  m("swords", 12, "knight-of-swords", "Knight of Swords",
    ["ambition", "decisive action", "urgency", "drive"],
    "Charging in with conviction. The Knight of Swords moves fast and cuts cleanly — sometimes too fast.",
    "Recklessness, abrasive communication, action without plan.",
    "Intensity that needs slowing down. Pace matters.",
    "Decisive action wins, if the strategy is sound.",
    "Move decisively — but check the plan once before charging."),

  m("swords", 13, "queen-of-swords", "Queen of Swords",
    ["clarity", "independence", "honesty", "sharp judgement"],
    "Clear-eyed, direct, and uncompromising on truth. The Queen of Swords cuts through fog with both honesty and fairness.",
    "Coldness, cruelty, bitterness, judgement without warmth.",
    "Direct, honest communication required. Soften the words, but not the truth.",
    "Cut through the noise. Your judgement is sharp; use it.",
    "Be honest, without cruelty. Both matter."),

  m("swords", 14, "king-of-swords", "King of Swords",
    ["intellect", "authority", "discipline", "fair judgement"],
    "Wisdom backed by experience. The King of Swords combines intellect and ethics — the judge you would want on your case.",
    "Tyranny, abuse of intellect, cold logic without humanity.",
    "A clear, principled partner — or the need to bring more reason into a heated moment.",
    "Apply structured thinking. The right answer is logical and humane.",
    "Lead with clear thinking and clear ethics. Both, not either."),

  // ============ PENTACLES (Earth — body, money, work, manifestation) ============
  m("pentacles", 1, "ace-of-pentacles", "Ace of Pentacles",
    ["new opportunity", "abundance", "manifestation", "prosperity"],
    "A new seed of material opportunity. The Ace of Pentacles offers the foundation of something tangible — money, work, health, or home.",
    "Missed opportunity, scarcity mindset, ungrounded plans.",
    "A grounded, practical new beginning. Building together.",
    "A new financial or career opportunity. Plant it carefully.",
    "Plant one practical seed today. Tend it daily."),

  m("pentacles", 2, "two-of-pentacles", "Two of Pentacles",
    ["balance", "juggling", "flexibility", "priorities"],
    "Juggling cups, plates, and life. The Two of Pentacles honors flexibility — and warns that you are doing too many things at once.",
    "Overwhelm, dropped balls, imbalance, financial chaos.",
    "Balancing relationship with everything else. Time is the currency.",
    "Juggling projects. Drop one, deliver two well.",
    "Pick what you will drop. You cannot hold it all."),

  m("pentacles", 3, "three-of-pentacles", "Three of Pentacles",
    ["collaboration", "teamwork", "craftsmanship", "skill"],
    "Three skilled hands building together. The Three of Pentacles celebrates craft and collaboration — the right people at the right table.",
    "Working alone when you should be collaborating, mismatched team, skill gaps.",
    "Working as a real team. Co-creating something.",
    "A collaborative project showcases your craft. Bring others in.",
    "Collaborate. Solo is slower."),

  m("pentacles", 4, "four-of-pentacles", "Four of Pentacles",
    ["holding on", "security", "control", "saving"],
    "Holding tightly to what you have. The Four of Pentacles values security — and warns when holding becomes hoarding.",
    "Loosening grip, generosity, releasing fear of loss.",
    "Holding on too tightly. Loosen the grip; love is not a possession.",
    "Financial security focus. Save, but do not hoard at the cost of growth.",
    "Hold what matters. Loosen what is just fear."),

  m("pentacles", 5, "five-of-pentacles", "Five of Pentacles",
    ["hardship", "scarcity", "isolation", "asking for help"],
    "Two figures in cold weather, light shining nearby unnoticed. The Five of Pentacles names hardship — and the unseen help that is closer than you think.",
    "Recovery, end of hardship, accepting help, finding shelter.",
    "Going through a hard chapter together. Lean on each other.",
    "A financial setback, but help is available if you ask.",
    "Ask for help. The light is closer than the dark suggests."),

  m("pentacles", 6, "six-of-pentacles", "Six of Pentacles",
    ["generosity", "giving and receiving", "balance", "support"],
    "Coins shared with care. The Six of Pentacles honors the balance of giving and receiving — and the dignity of both sides.",
    "Imbalance in giving, strings attached, taking advantage.",
    "Balanced give-and-take. Or restoring fairness if it has tipped.",
    "Mentorship, fair pay, or recognition of contribution.",
    "Give without strings. Receive without shame."),

  m("pentacles", 7, "seven-of-pentacles", "Seven of Pentacles",
    ["patience", "long-term view", "investment", "evaluation"],
    "Pausing to evaluate what you have grown. The Seven of Pentacles rewards patience and long-term thinking over quick fixes.",
    "Impatience, abandoning a project too early, short-term thinking.",
    "Evaluate where the relationship is heading. Slow growth is still growth.",
    "Mid-project check-in. Is this still the right path?",
    "Be patient. The harvest is not yet."),

  m("pentacles", 8, "eight-of-pentacles", "Eight of Pentacles",
    ["mastery", "dedication", "skill-building", "craftsmanship"],
    "Heads down, refining the craft. The Eight of Pentacles honors the slow accumulation of mastery — the unglamorous middle of getting good.",
    "Perfectionism, going through the motions, skill stagnation.",
    "Investing in becoming a better partner. Practice is love.",
    "Skill-building phase. Heads down; mastery is forming.",
    "Practice daily. Mastery is built in unwitnessed hours."),

  m("pentacles", 9, "nine-of-pentacles", "Nine of Pentacles",
    ["independence", "self-sufficiency", "luxury", "earned reward"],
    "A garden built by your own hands, enjoyed alone. The Nine of Pentacles honors independence and the rewards of self-sufficient work.",
    "Dependence on others, financial stress, hollow luxury.",
    "Self-sufficient and content. Ready to share life, not be completed by another.",
    "Earned reward. Take a moment to enjoy what you built.",
    "Enjoy what you built. Independence is its own pleasure."),

  m("pentacles", 10, "ten-of-pentacles", "Ten of Pentacles",
    ["wealth", "legacy", "family", "long-term security"],
    "Generational stability. The Ten of Pentacles celebrates what is built to outlast you — wealth, family, legacy, home.",
    "Family conflict over money or inheritance, short-term thinking.",
    "Long-haul family life. Building something that lasts.",
    "Long-term financial stability. Building generational wealth.",
    "Build for the next generation. Plant trees you will not sit under."),

  m("pentacles", 11, "page-of-pentacles", "Page of Pentacles",
    ["new study", "ambition", "groundedness", "potential"],
    "Studying something practical with seriousness. The Page of Pentacles begins the long apprenticeship into mastery and material reward.",
    "Procrastination, lack of focus, idea without follow-through.",
    "A grounded, learning-oriented new connection.",
    "A new study, course, or skill investment. Take it seriously.",
    "Start the study. Mastery begins with one chapter."),

  m("pentacles", 12, "knight-of-pentacles", "Knight of Pentacles",
    ["reliability", "patience", "hard work", "consistency"],
    "Slow, steady, and unfailingly reliable. The Knight of Pentacles honors the discipline of showing up — every day, no matter the weather.",
    "Stubbornness, boredom, getting stuck in routine, refusing to adapt.",
    "Reliable, slow-building love. Not exciting — exciting is not the point.",
    "Steady progress. Keep showing up; the compound effect is real.",
    "Show up. Consistency outperforms intensity."),

  m("pentacles", 13, "queen-of-pentacles", "Queen of Pentacles",
    ["nurturing", "practical care", "resourcefulness", "home"],
    "Practical care, generous resources, a warm home. The Queen of Pentacles makes the world livable through everyday tending.",
    "Self-neglect, smothering, work-life imbalance, materialism.",
    "A grounded, nurturing partner. Or the call to bring more care to daily life together.",
    "Resource the team. Practical leadership wins long-term.",
    "Tend to the everyday. The dishes done are an act of love."),

  m("pentacles", 14, "king-of-pentacles", "King of Pentacles",
    ["wealth", "stability", "long-term success", "earned authority"],
    "Built it themselves, brick by brick. The King of Pentacles honors slow-earned success — material, professional, and personal.",
    "Greed, materialism without meaning, controlling money, financial stress.",
    "A stable, providing partner — or the maturity to provide for yourself first.",
    "Earned authority. The long game pays off now.",
    "Think in decades, not quarters."),
];

// ============ HELPERS ============

export const getCard = (slug: string) => deck.find(c => c.slug === slug);
export const majorArcana = () => deck.filter(c => c.arcana === "major").sort((a,b) => a.number - b.number);
export const minorBySuit = (suit: Suit) => deck.filter(c => c.suit === suit).sort((a,b) => a.number - b.number);
export const allSuits: Suit[] = ["wands", "cups", "swords", "pentacles"];
export const suitLabel: Record<Suit, string> = {
  wands: "Wands",
  cups: "Cups",
  swords: "Swords",
  pentacles: "Pentacles",
};
export const suitElement: Record<Suit, string> = {
  wands: "Fire — passion, creation, action",
  cups: "Water — emotion, love, intuition",
  swords: "Air — thought, conflict, truth",
  pentacles: "Earth — body, money, work",
};

// Cryptographically-secure random pick (browser-safe)
export const drawRandom = (rng?: () => number): TarotCard => {
  const r = rng ? rng() : Math.random();
  return deck[Math.floor(r * deck.length)];
};
